import type { ExtractionTemplate, PostProcessingRule } from '@/types/extraction'

export const defaultExtractionTemplates: ExtractionTemplate[] = [
  {
    id: 'latest-artifact-card',
    name: 'Latest Artifact Card Template',
    builtin: true,
    fields: [
      {
        key: 'artifact_id',
        label: 'Artifact ID',
        type: 'Text',
        required: false,
        instruction:
          '只提取原文明确出现的器物或遗迹编号（如 H125:1、M3:18、T3:3）；保留冒号等标点，不得把图号或图中序号当作器物编号。',
        evidence_kind: 'number',
      },
      {
        key: 'surface_color',
        label: 'Surface Color',
        type: 'Text',
        required: false,
        instruction: '只提取原文明示的表面颜色，不得根据黑白线图推断颜色。',
        evidence_kind: 'text',
      },
      {
        key: 'texture',
        label: 'Texture',
        type: 'Text',
        required: false,
        instruction: '提取原文明示的质地、胎质或材质，不得从器形或颜色推断。',
        evidence_kind: 'text',
      },
      {
        key: 'measurements',
        label: 'Measurements',
        type: 'Text',
        required: false,
        instruction:
          '提取与当前器物明确对应的高、口径、底径、宽、厚等尺寸；raw_value 保留原文，value 可规范单位，但不得推算缺失尺寸。',
        evidence_kind: 'text',
      },
      {
        key: 'morphological_description',
        label: 'Morphological Description',
        type: 'Text',
        required: false,
        instruction:
          '提取当前器物的口、颈、腹、底、足、纹饰等形态描述；不得合并同页其他器物的描述。',
        evidence_kind: 'text',
      },
      {
        key: 'category',
        label: 'Category',
        type: 'Text',
        required: false,
        instruction:
          '提取原文明示的器物类别；疑似 OCR 错字时 raw_value 保留原文，value 可给出有依据的规范名称，并标记 needs_review。',
        evidence_kind: 'text',
      },
      {
        key: 'figure_caption',
        label: 'Figure Caption',
        type: 'Text',
        required: false,
        instruction:
          '逐字提取包含图号、图中序号或器物编号的原始图注；不得用概括后的器物描述替代图注。',
        evidence_kind: 'caption',
      },
      {
        key: 'completeness',
        label: 'Completeness',
        type: 'Text',
        required: false,
        instruction: '只提取原文明示的完整、残、残片、复原或比例信息，不得根据线图推断。',
        evidence_kind: 'text',
      },
    ],
  },
  {
    id: 'basic-research',
    name: 'Basic Research Template',
    builtin: true,
    fields: [
      {
        key: 'site_id',
        label: 'Site / Context ID',
        type: 'Text',
        required: false,
        instruction: '提取每个器物号冒号前的字母、数字或符号，只保留遗迹号，不得包含冒号后的序号。',
        evidence_kind: 'number',
      },
      {
        key: 'sequence_no',
        label: 'Sequence Number',
        type: 'Text',
        required: false,
        instruction: '提取每个器物号冒号后的序号，只保留序号本身，不得混入图号或图中序号。',
        evidence_kind: 'number',
      },
      {
        key: 'measurements',
        label: 'Measurements',
        type: 'Text',
        required: false,
        instruction: '直接提取当前器物原句中的尺寸信息，不作推断或补充；如有多个数值，使用中文顿号“、”连接。',
        evidence_kind: 'text',
      },
      {
        key: 'morphological_description',
        label: 'Morphological Description',
        type: 'Text',
        required: false,
        instruction: '直接提取当前器物的外形描述原句，不进行总结、概括或补写。',
        evidence_kind: 'text',
      },
      {
        key: 'surface_color',
        label: 'Surface Color',
        type: 'Text',
        required: false,
        instruction: '直接提取原文明示的颜色；不得根据黑白线图、器形或材质推断。',
        evidence_kind: 'text',
      },
      {
        key: 'artifact_type_1',
        label: 'Artifact Type 1',
        type: 'Text',
        required: false,
        instruction: '提取玉器、陶器、石器、漆器等原文明示的大类；不得将具体器名或材质填入此字段。',
        evidence_kind: 'text',
      },
      {
        key: 'artifact_type_2',
        label: 'Artifact Type 2',
        type: 'Text',
        required: false,
        instruction: '提取器物号之前标注的具体器名；原文未重复标注时，可在同一连续器物条目组内沿用上一件器名。',
        evidence_kind: 'text',
      },
      {
        key: 'texture',
        label: 'Texture',
        type: 'Text',
        required: false,
        instruction: '直接提取器物材质、质地或胎质；注意与颜色、器型严格区分。',
        evidence_kind: 'text',
      },
      {
        key: 'completeness',
        label: 'Completeness',
        type: 'Text',
        required: false,
        instruction: '提取完整、残、残片、碎片、复原等原文明示信息；残碎器物也必须保留记录。',
        evidence_kind: 'text',
      },
      {
        key: 'figure_caption',
        label: 'Figure Caption',
        type: 'Text',
        required: false,
        instruction: '直接提取器物信息末尾括号内的图注内容，不得改写、概括或补充。',
        evidence_kind: 'caption',
      },
    ],
  },
  {
    id: 'typology-research',
    name: 'Typology Research Template',
    builtin: true,
    fields: [
      {
        key: 'artifact_id',
        label: 'Artifact ID',
        type: 'Text',
        required: false,
        evidence_kind: 'number',
      },
      { key: 'category', label: 'Category', type: 'Text', required: false },
      { key: 'type', label: 'Type', type: 'Text', required: false },
      { key: 'subtype', label: 'Subtype', type: 'Text', required: false },
      { key: 'shape', label: 'Shape', type: 'Text', required: false },
      { key: 'texture', label: 'Texture', type: 'Text', required: false },
      { key: 'measurements', label: 'Measurements', type: 'Text', required: false },
    ],
  },
  {
    id: 'stratigraphic-research',
    name: 'Stratigraphic Research Template',
    builtin: true,
    fields: [
      { key: 'context_id', label: 'Context ID', type: 'Text', required: false },
      { key: 'layer', label: 'Layer', type: 'Text', required: false },
      { key: 'unit', label: 'Unit', type: 'Text', required: false },
      { key: 'depth', label: 'Depth', type: 'Text', required: false },
      { key: 'period', label: 'Period', type: 'Text', required: false },
      { key: 'relationship', label: 'Relationship', type: 'Text', required: false },
      { key: 'finds_summary', label: 'Finds Summary', type: 'Text', required: false },
    ],
  },
  {
    id: 'artifact-restoration',
    name: 'Artifact Restoration Template',
    builtin: true,
    fields: [
      {
        key: 'artifact_id',
        label: 'Artifact ID',
        type: 'Text',
        required: false,
        evidence_kind: 'number',
      },
      { key: 'material', label: 'Material', type: 'Text', required: false },
      { key: 'damage', label: 'Damage', type: 'Text', required: false },
      { key: 'completeness', label: 'Completeness', type: 'Text', required: false },
      { key: 'repair_history', label: 'Repair History', type: 'Text', required: false },
      { key: 'restoration_plan', label: 'Restoration Plan', type: 'Text', required: false },
    ],
  },
]

export const defaultPostProcessingRules: PostProcessingRule[] = [
  {
    id: 'chinese-number-to-arabic',
    key: 'chinese_number_to_arabic',
    name: 'Chinese to Arabic Number Conversion',
    description: 'Automatically convert Chinese numbers to Arabic numerals.',
    example: '“一百” to “100”',
    handler: 'builtin',
    enabled: true,
    builtin: true,
  },
  {
    id: 'unit-standardization',
    key: 'unit_standardization',
    name: 'Unit Standardization',
    description: 'Format units to a consistent standard.',
    example: '“厘米” or “公分” both become “cm”',
    handler: 'builtin',
    enabled: true,
    builtin: true,
  },
  {
    id: 'punctuation-normalization',
    key: 'punctuation_normalization',
    name: 'Punctuation Normalization',
    description: 'Standardize punctuation from full-width to half-width, or vice versa.',
    example: '“Hello！” to “Hello!”',
    handler: 'builtin',
    enabled: true,
    builtin: true,
  },
  {
    id: 'space-removal',
    key: 'space_removal',
    name: 'Space Removal',
    description: 'Eliminate extra spaces to ensure cleaner extracted text.',
    example: '“Artifact   A” to “Artifact A”',
    handler: 'builtin',
    enabled: false,
    builtin: true,
  },
  {
    id: 'date-formatting',
    key: 'date_formatting',
    name: 'Date and Time Formatting',
    description: 'Standardize various date and time formats.',
    example: '“2026年7月15日” to “2026-07-15”',
    handler: 'builtin',
    enabled: false,
    builtin: true,
  },
]
