/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArchaeologicalCatalogs: typeof import('./../components/business/ArchaeologicalCatalogs.vue')['default']
    AssertionRules: typeof import('./../components/business/AssertionRules.vue')['default']
    ContentPreview: typeof import('./../components/business/ContentPreview.vue')['default']
    DocumentSheet: typeof import('./../components/business/DocumentSheet.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElResult: typeof import('element-plus/es')['ElResult']
    ExtractionDetails: typeof import('./../components/business/ExtractionDetails.vue')['default']
    ExtractionResults: typeof import('./../components/business/ExtractionResults.vue')['default']
    ExtractionSettings: typeof import('./../components/business/ExtractionSettings.vue')['default']
    ExtractionTemplateDialog: typeof import('./../components/business/ExtractionTemplateDialog.vue')['default']
    LabelConstraintSelector: typeof import('./../components/business/LabelConstraintSelector.vue')['default']
    LanguageToggle: typeof import('./../components/business/LanguageToggle.vue')['default']
    MachineVerificationWorkspace: typeof import('./../components/business/MachineVerificationWorkspace.vue')['default']
    PageNavigator: typeof import('./../components/business/PageNavigator.vue')['default']
    PageRangeDialog: typeof import('./../components/business/PageRangeDialog.vue')['default']
    PdfOverview: typeof import('./../components/business/PdfOverview.vue')['default']
    PostProcessingRulesDialog: typeof import('./../components/business/PostProcessingRulesDialog.vue')['default']
    ProcessingPanel: typeof import('./../components/business/ProcessingPanel.vue')['default']
    QualityEvaluationPanel: typeof import('./../components/business/QualityEvaluationPanel.vue')['default']
    RelatedPages: typeof import('./../components/business/RelatedPages.vue')['default']
    RematchReportDialog: typeof import('./../components/business/RematchReportDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VerificationRuleDialog: typeof import('./../components/business/VerificationRuleDialog.vue')['default']
    VerificationSummary: typeof import('./../components/business/VerificationSummary.vue')['default']
    VersionHistory: typeof import('./../components/business/VersionHistory.vue')['default']
  }
}
